# Generated by Django 2.2.4 on 2019-08-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(max_length=100)),
                ('em', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=12)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
