# Generated by Django 2.2.4 on 2019-08-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('img', models.ImageField(default='', upload_to='blog')),
            ],
        ),
    ]
